# Generated by Django 4.2.20 on 2025-04-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoDataBase', '0004_inventory_shop_remove_characterappearance_boots_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='image_url',
            new_name='image_character_url',
        ),
        migrations.AddField(
            model_name='shop',
            name='image_preview_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='type',
            field=models.CharField(choices=[('hair', 'Hair'), ('headwear', 'Headwear'), ('top', 'Top'), ('bottom', 'Bottom'), ('boots', 'Boots'), ('skin', 'Skin')], max_length=20),
        ),
    ]
