# Generated by Django 4.2.20 on 2025-04-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoDataBase', '0007_shop_is_unlocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='is_purchased',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='is_unlocked',
        ),
        migrations.AddField(
            model_name='inventory',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
