# Generated by Django 4.2.20 on 2025-04-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoDataBase', '0009_inventory_is_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
