# Generated by Django 4.2.20 on 2025-05-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoDataBase', '0011_alter_shop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='base_reward_gold',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='task',
            name='base_reward_xp',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Medium'), (4, 'Hard'), (5, 'Very Hard')], default=3),
        ),
        migrations.AlterField(
            model_name='task',
            name='reward_gold',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='reward_xp',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
