# Generated by Django 4.2.20 on 2025-05-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoDataBase', '0014_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ranks/'),
        ),
    ]
