# Generated by Django 4.2.20 on 2025-05-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoDataBase', '0013_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required_xp', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['required_xp'],
            },
        ),
    ]
