# Generated by Django 4.2.20 on 2025-05-15 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoDataBase', '0015_rank_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='required_xp',
        ),
        migrations.AddField(
            model_name='shop',
            name='required_rank',
            field=models.ForeignKey(blank=True, help_text='Минимальный ранг для разблокировки предмета', null=True, on_delete=django.db.models.deletion.SET_NULL, to='todoDataBase.rank'),
        ),
    ]
