# Generated by Django 4.2.20 on 2025-09-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoDataBase', '0017_alter_user_managers_taskcollaborator_friendship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcollaborator',
            name='collaboration_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ожидание'), (2, 'Принято'), (3, 'Отклонено')], default=1),
        ),
        migrations.AddField(
            model_name='taskcollaborator',
            name='collaboration_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Любой может завершить'), (2, 'Все должны завершить')], default=1),
        ),
    ]
