# Generated by Django 4.2.20 on 2025-09-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoDataBase', '0018_taskcollaborator_collaboration_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcollaborator',
            name='collaboration_status',
        ),
        migrations.RemoveField(
            model_name='taskcollaborator',
            name='collaboration_type',
        ),
    ]
