# Generated by Django 4.2.20 on 2025-09-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoDataBase', '0019_remove_taskcollaborator_collaboration_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='collaboration_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ожидание'), (2, 'Принято'), (3, 'Отклонено')], default=1),
        ),
    ]
