# Generated by Django 4.2.20 on 2025-04-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoDataBase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
