# Generated by Django 4.2.20 on 2025-04-28 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoDataBase', '0003_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_equipped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hair', 'Hair'), ('headwear', 'Headwear'), ('top', 'Top'), ('bootom', 'Bottom'), ('boots', 'Boots'), ('skin', 'Skin')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('required_xp', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('is_purchased', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='characterappearance',
            name='boots',
        ),
        migrations.RemoveField(
            model_name='characterappearance',
            name='character',
        ),
        migrations.RemoveField(
            model_name='characterappearance',
            name='glasses',
        ),
        migrations.RemoveField(
            model_name='characterappearance',
            name='hat',
        ),
        migrations.RemoveField(
            model_name='characterappearance',
            name='pants',
        ),
        migrations.RemoveField(
            model_name='characterappearance',
            name='shirt',
        ),
        migrations.RemoveField(
            model_name='characterappearance',
            name='sword',
        ),
        migrations.RemoveField(
            model_name='unlockedskin',
            name='skin',
        ),
        migrations.RemoveField(
            model_name='unlockedskin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useritem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='useritem',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='gold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='CharacterAppearance',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Skin',
        ),
        migrations.DeleteModel(
            name='UnlockedSkin',
        ),
        migrations.DeleteModel(
            name='UserItem',
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_inventory', to='todoDataBase.shop'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL),
        ),
    ]
