# Generated by Django 4.2.20 on 2025-04-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoDataBase', '0005_rename_image_url_shop_image_character_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='type',
            field=models.CharField(choices=[('hair', 'Hair'), ('headwear', 'Headwear'), ('top', 'Top'), ('bottom', 'Bottom'), ('boots', 'Boots')], max_length=20),
        ),
    ]
