# Generated by Django 4.2.20 on 2025-04-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoDataBase', '0006_alter_shop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
