# Generated by Django 4.2.20 on 2025-04-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoDataBase', '0008_remove_shop_is_purchased_remove_shop_is_unlocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
