# Generated by Django 4.2.20 on 2025-04-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoDataBase', '0010_shop_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='type',
            field=models.CharField(choices=[('hair', 'Hair/Headwear'), ('top', 'Top'), ('bottom', 'Bottom'), ('boots', 'Boots')], max_length=20),
        ),
    ]
